/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as UserRouteRouteImport } from './routes/_user/route'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as signRouteRouteImport } from './routes/(sign)/route'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as AdminSplatRouteImport } from './routes/admin/$'
import { Route as UserUserRouteImport } from './routes/_user/user'
import { Route as UserTodosRouteImport } from './routes/_user/todos'
import { Route as PublicProfileRouteImport } from './routes/_public/profile'
import { Route as PublicAboutRouteImport } from './routes/_public/about'
import { Route as signSignUpRouteImport } from './routes/(sign)/sign-up'
import { Route as signSignInRouteImport } from './routes/(sign)/sign-in'
import { Route as AdminSettingIndexRouteImport } from './routes/admin/setting/index'
import { Route as AdminPageIndexRouteImport } from './routes/admin/page/index'
import { Route as AdminMenuIndexRouteImport } from './routes/admin/menu/index'
import { Route as AdminMediaIndexRouteImport } from './routes/admin/media/index'
import { Route as AdminCategoryIndexRouteImport } from './routes/admin/category/index'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoApiTqTodosRouteImport } from './routes/demo/api.tq-todos'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as AdminPostsListRouteImport } from './routes/admin/posts/list'
import { Route as AdminPostsCreateRouteImport } from './routes/admin/posts/create'
import { Route as AdminPostsCategoryRouteImport } from './routes/admin/posts/category'
import { Route as AdminPostsPostIdRouteImport } from './routes/admin/posts/$postId'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const UserRouteRoute = UserRouteRouteImport.update({
  id: '/_user',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const signRouteRoute = signRouteRouteImport.update({
  id: '/(sign)',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSplatRoute = AdminSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AdminRouteRoute,
} as any)
const UserUserRoute = UserUserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserTodosRoute = UserTodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => UserRouteRoute,
} as any)
const PublicProfileRoute = PublicProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRouteRoute,
} as any)
const signSignUpRoute = signSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => signRouteRoute,
} as any)
const signSignInRoute = signSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => signRouteRoute,
} as any)
const AdminSettingIndexRoute = AdminSettingIndexRouteImport.update({
  id: '/setting/',
  path: '/setting/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPageIndexRoute = AdminPageIndexRouteImport.update({
  id: '/page/',
  path: '/page/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMenuIndexRoute = AdminMenuIndexRouteImport.update({
  id: '/menu/',
  path: '/menu/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMediaIndexRoute = AdminMediaIndexRouteImport.update({
  id: '/media/',
  path: '/media/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCategoryIndexRoute = AdminCategoryIndexRouteImport.update({
  id: '/category/',
  path: '/category/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiTqTodosRoute = DemoApiTqTodosRouteImport.update({
  id: '/demo/api/tq-todos',
  path: '/demo/api/tq-todos',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPostsListRoute = AdminPostsListRouteImport.update({
  id: '/posts/list',
  path: '/posts/list',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPostsCreateRoute = AdminPostsCreateRouteImport.update({
  id: '/posts/create',
  path: '/posts/create',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPostsCategoryRoute = AdminPostsCategoryRouteImport.update({
  id: '/posts/category',
  path: '/posts/category',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPostsPostIdRoute = AdminPostsPostIdRouteImport.update({
  id: '/posts/$postId',
  path: '/posts/$postId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/sign-in': typeof signSignInRoute
  '/sign-up': typeof signSignUpRoute
  '/about': typeof PublicAboutRoute
  '/profile': typeof PublicProfileRoute
  '/todos': typeof UserTodosRoute
  '/user': typeof UserUserRoute
  '/admin/$': typeof AdminSplatRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/posts/$postId': typeof AdminPostsPostIdRoute
  '/admin/posts/category': typeof AdminPostsCategoryRoute
  '/admin/posts/create': typeof AdminPostsCreateRoute
  '/admin/posts/list': typeof AdminPostsListRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/admin/category': typeof AdminCategoryIndexRoute
  '/admin/media': typeof AdminMediaIndexRoute
  '/admin/menu': typeof AdminMenuIndexRoute
  '/admin/page': typeof AdminPageIndexRoute
  '/admin/setting': typeof AdminSettingIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/sign-in': typeof signSignInRoute
  '/sign-up': typeof signSignUpRoute
  '/about': typeof PublicAboutRoute
  '/profile': typeof PublicProfileRoute
  '/todos': typeof UserTodosRoute
  '/user': typeof UserUserRoute
  '/admin/$': typeof AdminSplatRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminIndexRoute
  '/admin/posts/$postId': typeof AdminPostsPostIdRoute
  '/admin/posts/category': typeof AdminPostsCategoryRoute
  '/admin/posts/create': typeof AdminPostsCreateRoute
  '/admin/posts/list': typeof AdminPostsListRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/admin/category': typeof AdminCategoryIndexRoute
  '/admin/media': typeof AdminMediaIndexRoute
  '/admin/menu': typeof AdminMenuIndexRoute
  '/admin/page': typeof AdminPageIndexRoute
  '/admin/setting': typeof AdminSettingIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(sign)': typeof signRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/_user': typeof UserRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/(sign)/sign-in': typeof signSignInRoute
  '/(sign)/sign-up': typeof signSignUpRoute
  '/_public/about': typeof PublicAboutRoute
  '/_public/profile': typeof PublicProfileRoute
  '/_user/todos': typeof UserTodosRoute
  '/_user/user': typeof UserUserRoute
  '/admin/$': typeof AdminSplatRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/_public/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/posts/$postId': typeof AdminPostsPostIdRoute
  '/admin/posts/category': typeof AdminPostsCategoryRoute
  '/admin/posts/create': typeof AdminPostsCreateRoute
  '/admin/posts/list': typeof AdminPostsListRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/admin/category/': typeof AdminCategoryIndexRoute
  '/admin/media/': typeof AdminMediaIndexRoute
  '/admin/menu/': typeof AdminMenuIndexRoute
  '/admin/page/': typeof AdminPageIndexRoute
  '/admin/setting/': typeof AdminSettingIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/$'
    | '/sign-in'
    | '/sign-up'
    | '/about'
    | '/profile'
    | '/todos'
    | '/user'
    | '/admin/$'
    | '/demo/tanstack-query'
    | '/'
    | '/admin/'
    | '/admin/posts/$postId'
    | '/admin/posts/category'
    | '/admin/posts/create'
    | '/admin/posts/list'
    | '/api/auth/$'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/admin/category'
    | '/admin/media'
    | '/admin/menu'
    | '/admin/page'
    | '/admin/setting'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/sign-in'
    | '/sign-up'
    | '/about'
    | '/profile'
    | '/todos'
    | '/user'
    | '/admin/$'
    | '/demo/tanstack-query'
    | '/'
    | '/admin'
    | '/admin/posts/$postId'
    | '/admin/posts/category'
    | '/admin/posts/create'
    | '/admin/posts/list'
    | '/api/auth/$'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/admin/category'
    | '/admin/media'
    | '/admin/menu'
    | '/admin/page'
    | '/admin/setting'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/(sign)'
    | '/_public'
    | '/_user'
    | '/admin'
    | '/$'
    | '/(sign)/sign-in'
    | '/(sign)/sign-up'
    | '/_public/about'
    | '/_public/profile'
    | '/_user/todos'
    | '/_user/user'
    | '/admin/$'
    | '/demo/tanstack-query'
    | '/_public/'
    | '/admin/'
    | '/admin/posts/$postId'
    | '/admin/posts/category'
    | '/admin/posts/create'
    | '/admin/posts/list'
    | '/api/auth/$'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/admin/category/'
    | '/admin/media/'
    | '/admin/menu/'
    | '/admin/page/'
    | '/admin/setting/'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  signRouteRoute: typeof signRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  UserRouteRoute: typeof UserRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoApiTqTodosRoute: typeof DemoApiTqTodosRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_user': {
      id: '/_user'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof UserRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(sign)': {
      id: '/(sign)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof signRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$': {
      id: '/admin/$'
      path: '/$'
      fullPath: '/admin/$'
      preLoaderRoute: typeof AdminSplatRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_user/user': {
      id: '/_user/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserUserRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/_user/todos': {
      id: '/_user/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof UserTodosRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/_public/profile': {
      id: '/_public/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof PublicProfileRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/(sign)/sign-up': {
      id: '/(sign)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof signSignUpRouteImport
      parentRoute: typeof signRouteRoute
    }
    '/(sign)/sign-in': {
      id: '/(sign)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof signSignInRouteImport
      parentRoute: typeof signRouteRoute
    }
    '/admin/setting/': {
      id: '/admin/setting/'
      path: '/setting'
      fullPath: '/admin/setting'
      preLoaderRoute: typeof AdminSettingIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/page/': {
      id: '/admin/page/'
      path: '/page'
      fullPath: '/admin/page'
      preLoaderRoute: typeof AdminPageIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/menu/': {
      id: '/admin/menu/'
      path: '/menu'
      fullPath: '/admin/menu'
      preLoaderRoute: typeof AdminMenuIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/media/': {
      id: '/admin/media/'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/category/': {
      id: '/admin/category/'
      path: '/category'
      fullPath: '/admin/category'
      preLoaderRoute: typeof AdminCategoryIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/tq-todos': {
      id: '/demo/api/tq-todos'
      path: '/demo/api/tq-todos'
      fullPath: '/demo/api/tq-todos'
      preLoaderRoute: typeof DemoApiTqTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/posts/list': {
      id: '/admin/posts/list'
      path: '/posts/list'
      fullPath: '/admin/posts/list'
      preLoaderRoute: typeof AdminPostsListRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/posts/create': {
      id: '/admin/posts/create'
      path: '/posts/create'
      fullPath: '/admin/posts/create'
      preLoaderRoute: typeof AdminPostsCreateRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/posts/category': {
      id: '/admin/posts/category'
      path: '/posts/category'
      fullPath: '/admin/posts/category'
      preLoaderRoute: typeof AdminPostsCategoryRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/posts/$postId': {
      id: '/admin/posts/$postId'
      path: '/posts/$postId'
      fullPath: '/admin/posts/$postId'
      preLoaderRoute: typeof AdminPostsPostIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface signRouteRouteChildren {
  signSignInRoute: typeof signSignInRoute
  signSignUpRoute: typeof signSignUpRoute
}

const signRouteRouteChildren: signRouteRouteChildren = {
  signSignInRoute: signSignInRoute,
  signSignUpRoute: signSignUpRoute,
}

const signRouteRouteWithChildren = signRouteRoute._addFileChildren(
  signRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicProfileRoute: typeof PublicProfileRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicProfileRoute: PublicProfileRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

interface UserRouteRouteChildren {
  UserTodosRoute: typeof UserTodosRoute
  UserUserRoute: typeof UserUserRoute
}

const UserRouteRouteChildren: UserRouteRouteChildren = {
  UserTodosRoute: UserTodosRoute,
  UserUserRoute: UserUserRoute,
}

const UserRouteRouteWithChildren = UserRouteRoute._addFileChildren(
  UserRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminSplatRoute: typeof AdminSplatRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminPostsPostIdRoute: typeof AdminPostsPostIdRoute
  AdminPostsCategoryRoute: typeof AdminPostsCategoryRoute
  AdminPostsCreateRoute: typeof AdminPostsCreateRoute
  AdminPostsListRoute: typeof AdminPostsListRoute
  AdminCategoryIndexRoute: typeof AdminCategoryIndexRoute
  AdminMediaIndexRoute: typeof AdminMediaIndexRoute
  AdminMenuIndexRoute: typeof AdminMenuIndexRoute
  AdminPageIndexRoute: typeof AdminPageIndexRoute
  AdminSettingIndexRoute: typeof AdminSettingIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminSplatRoute: AdminSplatRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminPostsPostIdRoute: AdminPostsPostIdRoute,
  AdminPostsCategoryRoute: AdminPostsCategoryRoute,
  AdminPostsCreateRoute: AdminPostsCreateRoute,
  AdminPostsListRoute: AdminPostsListRoute,
  AdminCategoryIndexRoute: AdminCategoryIndexRoute,
  AdminMediaIndexRoute: AdminMediaIndexRoute,
  AdminMenuIndexRoute: AdminMenuIndexRoute,
  AdminPageIndexRoute: AdminPageIndexRoute,
  AdminSettingIndexRoute: AdminSettingIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  signRouteRoute: signRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
  UserRouteRoute: UserRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  SplatRoute: SplatRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoApiTqTodosRoute: DemoApiTqTodosRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
