/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as UserRouteRouteImport } from './routes/_user/route'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as signRouteRouteImport } from './routes/(sign)/route'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as AdminSplatRouteImport } from './routes/admin/$'
import { Route as UserUserRouteImport } from './routes/_user/user'
import { Route as UserTodosRouteImport } from './routes/_user/todos'
import { Route as PublicProfileRouteImport } from './routes/_public/profile'
import { Route as PublicAboutRouteImport } from './routes/_public/about'
import { Route as Public403RouteImport } from './routes/_public/403'
import { Route as signSignUpRouteImport } from './routes/(sign)/sign-up'
import { Route as signSignInRouteImport } from './routes/(sign)/sign-in'
import { Route as AdminSettingsIndexRouteImport } from './routes/admin/settings/index'
import { Route as AdminPageIndexRouteImport } from './routes/admin/page/index'
import { Route as AdminMenuIndexRouteImport } from './routes/admin/menu/index'
import { Route as AdminMediaIndexRouteImport } from './routes/admin/media/index'
import { Route as AdminCategoryIndexRouteImport } from './routes/admin/category/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as AdminProductsCategoryRouteImport } from './routes/admin/products/category'
import { Route as AdminPostsListRouteImport } from './routes/admin/posts/list'
import { Route as AdminPostsCreateRouteImport } from './routes/admin/posts/create'
import { Route as AdminPostsCategoryRouteImport } from './routes/admin/posts/category'
import { Route as AdminPostsPostIdRouteImport } from './routes/admin/posts/$postId'
import { Route as AdminProductsListIndexRouteImport } from './routes/admin/products/list/index'
import { Route as AdminProductsIdIndexRouteImport } from './routes/admin/products/$id/index'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const UserRouteRoute = UserRouteRouteImport.update({
  id: '/_user',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const signRouteRoute = signRouteRouteImport.update({
  id: '/(sign)',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AdminSplatRoute = AdminSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AdminRouteRoute,
} as any)
const UserUserRoute = UserUserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserTodosRoute = UserTodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => UserRouteRoute,
} as any)
const PublicProfileRoute = PublicProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRouteRoute,
} as any)
const Public403Route = Public403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => PublicRouteRoute,
} as any)
const signSignUpRoute = signSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => signRouteRoute,
} as any)
const signSignInRoute = signSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => signRouteRoute,
} as any)
const AdminSettingsIndexRoute = AdminSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPageIndexRoute = AdminPageIndexRouteImport.update({
  id: '/page/',
  path: '/page/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMenuIndexRoute = AdminMenuIndexRouteImport.update({
  id: '/menu/',
  path: '/menu/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMediaIndexRoute = AdminMediaIndexRouteImport.update({
  id: '/media/',
  path: '/media/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCategoryIndexRoute = AdminCategoryIndexRouteImport.update({
  id: '/category/',
  path: '/category/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsCategoryRoute = AdminProductsCategoryRouteImport.update({
  id: '/products/category',
  path: '/products/category',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPostsListRoute = AdminPostsListRouteImport.update({
  id: '/posts/list',
  path: '/posts/list',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPostsCreateRoute = AdminPostsCreateRouteImport.update({
  id: '/posts/create',
  path: '/posts/create',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPostsCategoryRoute = AdminPostsCategoryRouteImport.update({
  id: '/posts/category',
  path: '/posts/category',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPostsPostIdRoute = AdminPostsPostIdRouteImport.update({
  id: '/posts/$postId',
  path: '/posts/$postId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProductsListIndexRoute = AdminProductsListIndexRouteImport.update({
  id: '/products/list/',
  path: '/products/list/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProductsIdIndexRoute = AdminProductsIdIndexRouteImport.update({
  id: '/products/$id/',
  path: '/products/$id/',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/sign-in': typeof signSignInRoute
  '/sign-up': typeof signSignUpRoute
  '/403': typeof Public403Route
  '/about': typeof PublicAboutRoute
  '/profile': typeof PublicProfileRoute
  '/todos': typeof UserTodosRoute
  '/user': typeof UserUserRoute
  '/admin/$': typeof AdminSplatRoute
  '/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/posts/$postId': typeof AdminPostsPostIdRoute
  '/admin/posts/category': typeof AdminPostsCategoryRoute
  '/admin/posts/create': typeof AdminPostsCreateRoute
  '/admin/posts/list': typeof AdminPostsListRoute
  '/admin/products/category': typeof AdminProductsCategoryRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/category': typeof AdminCategoryIndexRoute
  '/admin/media': typeof AdminMediaIndexRoute
  '/admin/menu': typeof AdminMenuIndexRoute
  '/admin/page': typeof AdminPageIndexRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
  '/admin/products/$id': typeof AdminProductsIdIndexRoute
  '/admin/products/list': typeof AdminProductsListIndexRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/sign-in': typeof signSignInRoute
  '/sign-up': typeof signSignUpRoute
  '/403': typeof Public403Route
  '/about': typeof PublicAboutRoute
  '/profile': typeof PublicProfileRoute
  '/todos': typeof UserTodosRoute
  '/user': typeof UserUserRoute
  '/admin/$': typeof AdminSplatRoute
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminIndexRoute
  '/admin/posts/$postId': typeof AdminPostsPostIdRoute
  '/admin/posts/category': typeof AdminPostsCategoryRoute
  '/admin/posts/create': typeof AdminPostsCreateRoute
  '/admin/posts/list': typeof AdminPostsListRoute
  '/admin/products/category': typeof AdminProductsCategoryRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/category': typeof AdminCategoryIndexRoute
  '/admin/media': typeof AdminMediaIndexRoute
  '/admin/menu': typeof AdminMenuIndexRoute
  '/admin/page': typeof AdminPageIndexRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
  '/admin/products/$id': typeof AdminProductsIdIndexRoute
  '/admin/products/list': typeof AdminProductsListIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(sign)': typeof signRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/_user': typeof UserRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/(sign)/sign-in': typeof signSignInRoute
  '/(sign)/sign-up': typeof signSignUpRoute
  '/_public/403': typeof Public403Route
  '/_public/about': typeof PublicAboutRoute
  '/_public/profile': typeof PublicProfileRoute
  '/_user/todos': typeof UserTodosRoute
  '/_user/user': typeof UserUserRoute
  '/admin/$': typeof AdminSplatRoute
  '/_public/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/posts/$postId': typeof AdminPostsPostIdRoute
  '/admin/posts/category': typeof AdminPostsCategoryRoute
  '/admin/posts/create': typeof AdminPostsCreateRoute
  '/admin/posts/list': typeof AdminPostsListRoute
  '/admin/products/category': typeof AdminProductsCategoryRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/category/': typeof AdminCategoryIndexRoute
  '/admin/media/': typeof AdminMediaIndexRoute
  '/admin/menu/': typeof AdminMenuIndexRoute
  '/admin/page/': typeof AdminPageIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/products/$id/': typeof AdminProductsIdIndexRoute
  '/admin/products/list/': typeof AdminProductsListIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/$'
    | '/sign-in'
    | '/sign-up'
    | '/403'
    | '/about'
    | '/profile'
    | '/todos'
    | '/user'
    | '/admin/$'
    | '/'
    | '/admin/'
    | '/admin/posts/$postId'
    | '/admin/posts/category'
    | '/admin/posts/create'
    | '/admin/posts/list'
    | '/admin/products/category'
    | '/api/auth/$'
    | '/admin/category'
    | '/admin/media'
    | '/admin/menu'
    | '/admin/page'
    | '/admin/settings'
    | '/admin/products/$id'
    | '/admin/products/list'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/sign-in'
    | '/sign-up'
    | '/403'
    | '/about'
    | '/profile'
    | '/todos'
    | '/user'
    | '/admin/$'
    | '/'
    | '/admin'
    | '/admin/posts/$postId'
    | '/admin/posts/category'
    | '/admin/posts/create'
    | '/admin/posts/list'
    | '/admin/products/category'
    | '/api/auth/$'
    | '/admin/category'
    | '/admin/media'
    | '/admin/menu'
    | '/admin/page'
    | '/admin/settings'
    | '/admin/products/$id'
    | '/admin/products/list'
  id:
    | '__root__'
    | '/(sign)'
    | '/_public'
    | '/_user'
    | '/admin'
    | '/$'
    | '/(sign)/sign-in'
    | '/(sign)/sign-up'
    | '/_public/403'
    | '/_public/about'
    | '/_public/profile'
    | '/_user/todos'
    | '/_user/user'
    | '/admin/$'
    | '/_public/'
    | '/admin/'
    | '/admin/posts/$postId'
    | '/admin/posts/category'
    | '/admin/posts/create'
    | '/admin/posts/list'
    | '/admin/products/category'
    | '/api/auth/$'
    | '/admin/category/'
    | '/admin/media/'
    | '/admin/menu/'
    | '/admin/page/'
    | '/admin/settings/'
    | '/admin/products/$id/'
    | '/admin/products/list/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  signRouteRoute: typeof signRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  UserRouteRoute: typeof UserRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_user': {
      id: '/_user'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof UserRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(sign)': {
      id: '/(sign)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof signRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/admin/$': {
      id: '/admin/$'
      path: '/$'
      fullPath: '/admin/$'
      preLoaderRoute: typeof AdminSplatRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_user/user': {
      id: '/_user/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserUserRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/_user/todos': {
      id: '/_user/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof UserTodosRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/_public/profile': {
      id: '/_public/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof PublicProfileRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/403': {
      id: '/_public/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof Public403RouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/(sign)/sign-up': {
      id: '/(sign)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof signSignUpRouteImport
      parentRoute: typeof signRouteRoute
    }
    '/(sign)/sign-in': {
      id: '/(sign)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof signSignInRouteImport
      parentRoute: typeof signRouteRoute
    }
    '/admin/settings/': {
      id: '/admin/settings/'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/page/': {
      id: '/admin/page/'
      path: '/page'
      fullPath: '/admin/page'
      preLoaderRoute: typeof AdminPageIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/menu/': {
      id: '/admin/menu/'
      path: '/menu'
      fullPath: '/admin/menu'
      preLoaderRoute: typeof AdminMenuIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/media/': {
      id: '/admin/media/'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/category/': {
      id: '/admin/category/'
      path: '/category'
      fullPath: '/admin/category'
      preLoaderRoute: typeof AdminCategoryIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products/category': {
      id: '/admin/products/category'
      path: '/products/category'
      fullPath: '/admin/products/category'
      preLoaderRoute: typeof AdminProductsCategoryRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/posts/list': {
      id: '/admin/posts/list'
      path: '/posts/list'
      fullPath: '/admin/posts/list'
      preLoaderRoute: typeof AdminPostsListRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/posts/create': {
      id: '/admin/posts/create'
      path: '/posts/create'
      fullPath: '/admin/posts/create'
      preLoaderRoute: typeof AdminPostsCreateRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/posts/category': {
      id: '/admin/posts/category'
      path: '/posts/category'
      fullPath: '/admin/posts/category'
      preLoaderRoute: typeof AdminPostsCategoryRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/posts/$postId': {
      id: '/admin/posts/$postId'
      path: '/posts/$postId'
      fullPath: '/admin/posts/$postId'
      preLoaderRoute: typeof AdminPostsPostIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/products/list/': {
      id: '/admin/products/list/'
      path: '/products/list'
      fullPath: '/admin/products/list'
      preLoaderRoute: typeof AdminProductsListIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/products/$id/': {
      id: '/admin/products/$id/'
      path: '/products/$id'
      fullPath: '/admin/products/$id'
      preLoaderRoute: typeof AdminProductsIdIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface signRouteRouteChildren {
  signSignInRoute: typeof signSignInRoute
  signSignUpRoute: typeof signSignUpRoute
}

const signRouteRouteChildren: signRouteRouteChildren = {
  signSignInRoute: signSignInRoute,
  signSignUpRoute: signSignUpRoute,
}

const signRouteRouteWithChildren = signRouteRoute._addFileChildren(
  signRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  Public403Route: typeof Public403Route
  PublicAboutRoute: typeof PublicAboutRoute
  PublicProfileRoute: typeof PublicProfileRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  Public403Route: Public403Route,
  PublicAboutRoute: PublicAboutRoute,
  PublicProfileRoute: PublicProfileRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

interface UserRouteRouteChildren {
  UserTodosRoute: typeof UserTodosRoute
  UserUserRoute: typeof UserUserRoute
}

const UserRouteRouteChildren: UserRouteRouteChildren = {
  UserTodosRoute: UserTodosRoute,
  UserUserRoute: UserUserRoute,
}

const UserRouteRouteWithChildren = UserRouteRoute._addFileChildren(
  UserRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminSplatRoute: typeof AdminSplatRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminPostsPostIdRoute: typeof AdminPostsPostIdRoute
  AdminPostsCategoryRoute: typeof AdminPostsCategoryRoute
  AdminPostsCreateRoute: typeof AdminPostsCreateRoute
  AdminPostsListRoute: typeof AdminPostsListRoute
  AdminProductsCategoryRoute: typeof AdminProductsCategoryRoute
  AdminCategoryIndexRoute: typeof AdminCategoryIndexRoute
  AdminMediaIndexRoute: typeof AdminMediaIndexRoute
  AdminMenuIndexRoute: typeof AdminMenuIndexRoute
  AdminPageIndexRoute: typeof AdminPageIndexRoute
  AdminSettingsIndexRoute: typeof AdminSettingsIndexRoute
  AdminProductsIdIndexRoute: typeof AdminProductsIdIndexRoute
  AdminProductsListIndexRoute: typeof AdminProductsListIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminSplatRoute: AdminSplatRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminPostsPostIdRoute: AdminPostsPostIdRoute,
  AdminPostsCategoryRoute: AdminPostsCategoryRoute,
  AdminPostsCreateRoute: AdminPostsCreateRoute,
  AdminPostsListRoute: AdminPostsListRoute,
  AdminProductsCategoryRoute: AdminProductsCategoryRoute,
  AdminCategoryIndexRoute: AdminCategoryIndexRoute,
  AdminMediaIndexRoute: AdminMediaIndexRoute,
  AdminMenuIndexRoute: AdminMenuIndexRoute,
  AdminPageIndexRoute: AdminPageIndexRoute,
  AdminSettingsIndexRoute: AdminSettingsIndexRoute,
  AdminProductsIdIndexRoute: AdminProductsIdIndexRoute,
  AdminProductsListIndexRoute: AdminProductsListIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  signRouteRoute: signRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
  UserRouteRoute: UserRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  SplatRoute: SplatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
